spring.application.name=getttsapi
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Uzbekvoice API
uzbekvoice.api.key=7b0f10ea-32c9-429a-a42a-24fdc4e4ed43:17b76b00-545d-4952-b400-01080f3416c7
uzbekvoice.api.url=https://uzbekvoice.ai/api/v1

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Telegram Bot Configuration
telegram.bot.token=8963185673:AAGFxwZkdOV_E7TuiHsBb2LNMqjacy-SZrQ
telegram.bot.username=matndan_ovozga_bot
